Added Neumorphism Login Form
Dezenix/frontend-html-css-js pull request #131
Opened 2022-03-13 19:14 UTC by Sulagna-Dutta-Roy

# Issue No
Fixes:   #130

2022-03-14 15:17 UTC, Abirpal202049 requested changes

2022-03-14 15:17 UTC, Abirpal202049 commented on Login_Forms/Neumorphism_Form/Code/style.css
> +
Target the button by class or id

2022-03-14 15:17 UTC, Abirpal202049 commented on Login_Forms/Neumorphism_Form/Code/style.css
> +}
Change the shadow of the button

2022-03-16 13:56 UTC, Abirpal202049 commented
Update the Readme file based on the current changes

2022-03-16 16:36 UTC, Sulagna-Dutta-Roy commented
Updated the readme. Please check

2022-03-17 14:21 UTC, Abirpal202049 approved these changes

2022-03-17 14:22 UTC, merged