Added Anime profile pic genrator to the current repository
Dezenix/frontend-html-css-js pull request #157
Opened 2022-04-17 13:31 UTC by AmolShelke2

Hey, project admin as you assign me the issue that I will be adding my anime app to the current repository I'm creating the pull request regarding that I have added my project to the repository please go through my pull request and I hope that you will merge my pull request thank for assigning me the issue.

#fixes iSSUE [156](https://github.com/Dezenix/frontend-html-css-js/issues/156)

2022-04-17 15:19 UTC, Abirpal202049 requested changes

2022-04-17 15:19 UTC, Abirpal202049 commented on Anime App/style.css
> +}
Target the body by id or class

2022-04-17 15:19 UTC, Abirpal202049 commented on Anime App/README.md
> +[Amol Shelke❤️‍🔥](https://github.com/AmolShelke2)
Change the readme according to the rest of the projects

2022-04-17 15:30 UTC, AmolShelke2 commented
I will fixed it
Thanks

On Sun, Apr 17, 2022, 8:50 PM Abir Pal ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Anime App/style.css
> <https://github.com/Dezenix/frontend-html-css-js/pull/157#discussion_r851769936>
> :
>
> > +
>
> +body {
>
> +  font-family: "Poppins", sans-serif;
>
> +  font-weight: normal;
>
> +  background: linear-gradient(to right, #00afff, #00ff6c);
>
> +  display: flex;
>
> +  flex-direction: column;
>
> +  justify-content: center;
>
> +  height: 100vh;
>
> +  align-items: center;
>
> +  overflow: hidden;
>
> +  margin: 0;
>
> +}
>
>
> Target the body by id or class
> ------------------------------
>
> In Anime App/README.md
> <https://github.com/Dezenix/frontend-html-css-js/pull/157#discussion_r851770108>
> :
>
> > +# Anime App
>
> +
>
> +A simple anime app created with HTML CSS and JavaScript and with third party api catboys.Api it is really meant for beginners who don't have the knowledge of working with web apis in javaScript
>
> +
>
> +## Tech Stacks Used
>
> +
>
> +![HTML](https://img.shields.io/badge/html5%20-%23E34F26.svg?&style=for-the-badge&logo=html5&logoColor=white)
>
> +![CSS](https://img.shields.io/badge/css3%20-%231572B6.svg?&style=for-the-badge&logo=css3&logoColor=white)
>
> +![JS](https://img.shields.io/badge/javascript%20-%23323330.svg?&style=for-the-badge&logo=javascript&logoColor=%23F7DF1E)
>
> +
>
> +## owner of the Project
>
> +
>
> +[Amol Shelke❤️‍🔥](https://github.com/AmolShelke2)
>
>
> Change the readme according to the rest of the projects
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dezenix/frontend-html-css-js/pull/157#pullrequestreview-943959826>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWWDINRMNTQHGSNR3M4NGWDVFQT2LANCNFSM5TT4JZ7A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-18 11:12 UTC, AmolShelke2 commented
@Abirpal202049 I have done changes please give it a look

2022-04-18 11:39 UTC, Abirpal202049 approved these changes

2022-04-18 11:39 UTC, merged

2022-04-18 11:41 UTC, AmolShelke2 commented
Thank you so much @Abirpal202049🙂