Added Responsive Profile Card
Dezenix/frontend-html-css-js pull request #158
Opened 2022-04-17 19:49 UTC by Sulagna-Dutta-Roy

Fixes: #155 
Tech stack: Html5,Css,Javascript

![Profile Card](https://user-images.githubusercontent.com/72568715/163730048-5f848626-2dad-4e00-8b47-f726ef715707.PNG)
![Profile Card1](https://user-images.githubusercontent.com/72568715/163730050-33eee7ef-236c-4a92-aec3-9fd1290626b0.PNG)

2022-04-18 17:02 UTC, Sulagna-Dutta-Roy commented
@Abirpal202049 @nandini7637 kindly review this PR

2022-04-18 20:59 UTC, Abirpal202049 requested changes

2022-04-18 20:59 UTC, Abirpal202049 commented on Cards/Personal Profile Card/code/style.css
> +}
target the body by class or id

2022-04-18 20:59 UTC, Abirpal202049 commented on Cards/Personal Profile Card/code/style.css
> +}
Else everything is Ok

2022-04-18 21:41 UTC, Sulagna-Dutta-Roy commented
Done the changes. Kindly check

2022-04-19 04:49 UTC, Abirpal202049 approved these changes

2022-04-19 04:49 UTC, merged