Digital clock
Dezenix/frontend-html-css-js pull request #28
Opened 2021-12-17 13:43 UTC by DragonUncaged

#26

2021-12-21 11:49 UTC, Ovenoboyo approved these changes

2021-12-22 14:13 UTC, thepranaygupta approved these changes

2021-12-22 15:14 UTC, nandini7637 requested changes
There is issue with responsiveness, please make requires changes
![image](https://user-images.githubusercontent.com/76876383/147114000-185f9d45-5e20-45b5-87cb-f57bc9366a1a.png)

2021-12-24 07:27 UTC, saikatmu31 approved these changes

2021-12-26 05:51 UTC, Abirpal202049 approved these changes

2021-12-26 07:19 UTC, Abirpal202049 requested changes
Make it responsive

2021-12-26 07:21 UTC, saikatmu31 requested changes
Improve the Responsiveness by Using media query

2021-12-26 10:16 UTC, Abirpal202049 commented
@DragonUncaged put your files inside proper folder

2021-12-27 12:29 UTC, Ovenoboyo requested changes

2021-12-27 12:29 UTC, Ovenoboyo commented on Clock/Digital_Clock/code/index.js
> +    var am = "AM";
Prefer using "const" instead of "let" wherever possible

2021-12-27 12:29 UTC, Ovenoboyo commented on Clock/Digital_Clock/code/index.js
> +var interval = setInterval(clock,1000)
Avoid using var altogether. Instead use let or const

2022-01-05 08:11 UTC, nandini7637 commented
@DragonUncaged have you worked on the changes?

2022-01-07 06:46 UTC, saikatmu31 approved these changes

2022-01-09 18:50 UTC, nandini7637 commented
@DragonUncaged  updates? 
Should I close this PR?

2022-01-10 20:54 UTC, DragonUncaged commented
> @DragonUncaged updates? Should I close this PR?

NO

2022-01-13 10:00 UTC, nandini7637 commented
> > @DragonUncaged updates? Should I close this PR?
> 
> NO I will be doing it

Deadline for this is Saturday

2022-01-14 14:22 UTC, DragonUncaged commented
![Digital-clock-demoo](https://user-images.githubusercontent.com/72241207/149529892-29d8f29a-18f7-4ace-bbf7-75de0e0fa835.gif)

- [x] Changes Regarding the responsiveness
Made as much responsive as i can with retaining the beauty of the clock
- [x] Changes Regarding the JavaScript variable
 cannot use const everywhere but tried to use where ever possible.

2022-01-14 16:18 UTC, Abirpal202049 approved these changes

2022-01-15 07:00 UTC, thepranaygupta approved these changes

2022-01-15 07:44 UTC, merged