added neumorphism toggle buttons
Dezenix/frontend-html-css-js pull request #44
Opened 2021-12-25 07:20 UTC by suyogkokaje

2021-12-25 07:24 UTC, suyogkokaje commented
Sorry for again making PR. But I faced some issue. So I closed previous PR and made again. Please have a look.

2021-12-25 08:58 UTC, nandini7637 requested changes
Kindly follow the folder pattern
Buttons->Toggle buttons_01->Code(includes html, css file)
                                                ->Readme

2021-12-25 10:15 UTC, suyogkokaje commented
@nandini7637 please have a look.

2021-12-25 14:10 UTC, bhavesh-chaudhari approved these changes
Requested changes have been made. LGTM.

2021-12-25 17:43 UTC, nandini7637 approved these changes

2021-12-26 06:03 UTC, Abirpal202049 requested changes

2021-12-26 06:03 UTC, Abirpal202049 commented on Buttons/Toggle buttons_01/code/style.css
> +    color: #fff;
Change this to #1f1f1f it think this will be better and visible

2021-12-26 06:04 UTC, Abirpal202049 requested changes

2021-12-26 06:04 UTC, Abirpal202049 commented on Buttons/Toggle buttons_01/code/style.css
> +    color: #fff;
Change the color from white to black for more visibility . I think #1f1f1f will be better

2021-12-26 08:00 UTC, saikatmu31 approved these changes

2021-12-26 09:48 UTC, suyogkokaje commented
@Abirpal202049 please have a look.

2021-12-26 09:48 UTC, Abirpal202049 approved these changes

2021-12-26 10:06 UTC, merged