Code added for Issue Dezenix#33 10Doc by Arpan Sharma
Dezenix/frontend-html-css-js pull request #48
Opened 2021-12-25 17:19 UTC by arpansharma-11

This PR is for the assigned issue Dezenix#33 10DoC Hover UI Effect.

2021-12-26 06:56 UTC, saikatmu31 requested changes
Also add a readme file

2021-12-26 06:56 UTC, saikatmu31 commented on UI HOVER EFFECT/code/style.css
> +}
Avoid Targeting the Elements by HTML tags instead use some class or ID

2021-12-26 06:59 UTC, Abirpal202049 commented
Yes make the changes as mentioned by @saikatmu31

2021-12-27 12:22 UTC, Ovenoboyo requested changes
If script.js is empty and unnecessary, please delete it. And please use clear folder naming conventions. For example you may put all your javascript code in a folder called "js", your css in a folder called "css" instead of putting it all inside "code"

2021-12-27 12:22 UTC, Ovenoboyo commented on UI HOVER EFFECT/code/style.css
> +
Please remove extra whitespaces inside and after css classes. For styling guidelines you can refer to [this](https://google.github.io/styleguide/htmlcssguide.html)

2021-12-27 12:22 UTC, Ovenoboyo commented on UI HOVER EFFECT/code/tilt.js
> +    class t {
Please avoid making spaghetti by declaring a class inside a function then instantiating and returning it in an anonymous function. Write clean code by separating all components and write comments such that it clearly shows the flow of your code.

2021-12-27 12:22 UTC, Ovenoboyo commented on UI HOVER EFFECT/code/tilt.js
> +        getElementListener() {
also make use of [private class methods and properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) if your method or property isn't going to be referenced from outside the class

2021-12-27 12:22 UTC, Ovenoboyo commented on UI HOVER EFFECT/code/tilt.js
> +            for (var s in e)
Please prefer using {}. Even though not using them is syntactically correct, it usually makes the code difficult to read and understand

2021-12-27 12:22 UTC, Ovenoboyo commented on UI HOVER EFFECT/code/tilt.js
> +                    "max-glare": 1,
avoid using "-" when defining properties in a JS object. Instead prefer using "_"

2021-12-27 16:50 UTC, closed without merging