Fix : Responsive Accordion #49
Dezenix/frontend-html-css-js pull request #52
Opened 2021-12-26 10:46 UTC by Im-Abhi

Issue Related : #49
Preview 

![Accodion_Preview](https://user-images.githubusercontent.com/86161191/147405769-09a40970-c554-4bc4-90e4-7311a0165a8a.png)

2021-12-26 10:47 UTC, Im-Abhi commented
@nandini7637 Please review the PR for the same . Thank you

2021-12-27 04:27 UTC, nandini7637 requested changes
1- The hover color for small devices is black so if you could change that, it will be great
2- Increase font of the dopdown content.
3- Remove the readme of progress bar

else everything looks nice
good work!

2021-12-27 12:08 UTC, Ovenoboyo requested changes

2021-12-27 12:08 UTC, Ovenoboyo commented on Accordion/Responsive_Accordion_01/code/style.css
> +  .accordion-bral {
Indentation here seems weird. For guidelines you can refer to [this](https://google.github.io/styleguide/htmlcssguide.html)

2021-12-27 12:08 UTC, Ovenoboyo commented on Accordion/Responsive_Accordion_01/code/style.css
> +html {
Also avoid directly styling html tags. If possible please move this to a css class

2021-12-27 16:00 UTC, Im-Abhi commented
@nandini7637 @Ovenoboyo  I have completed the requested changes please review them. Thank you

2021-12-27 16:02 UTC, Ovenoboyo approved these changes

2021-12-27 16:21 UTC, Abirpal202049 approved these changes

2021-12-27 16:27 UTC, nandini7637 approved these changes

2021-12-28 05:57 UTC, thepranaygupta approved these changes
LGTM 👍

2021-12-28 06:01 UTC, saikatmu31 approved these changes

2021-12-28 06:01 UTC, merged