Added Footer
Dezenix/frontend-html-css-js pull request #70
Opened 2021-12-31 16:20 UTC by Sumandeep-Kaur

Fixes: #66

2022-01-01 08:22 UTC, nandini7637 approved these changes

2022-01-01 08:23 UTC, nandini7637 commented
@Sumandeep-Kaur make a folder of Footer_01 and inside that add code and assets

2022-01-01 10:32 UTC, Sumandeep-Kaur commented
> @Sumandeep-Kaur make a folder of Footer_01 and inside that add code and assets

Made the changes, Please have a look!

2022-01-02 17:41 UTC, thepranaygupta commented on Footers/code/style.css
> +*/
please remove this commented code.

2022-01-02 17:42 UTC, thepranaygupta requested changes

2022-01-02 17:42 UTC, thepranaygupta commented on Footers/code/style.css
> +*/
please remove this commented code

2022-01-03 06:12 UTC, Sumandeep-Kaur commented
Removed! @thepranaygupta

2022-01-05 08:12 UTC, merged