feat: added contact us form
Dezenix/frontend-html-css-js pull request #71
Opened 2022-01-01 03:33 UTC by suyogkokaje

Please have a look.

2022-01-06 17:05 UTC, nandini7637 requested changes
Add class to body while adding css, people might have problem using it in future

2022-01-07 04:17 UTC, nandini7637 approved these changes

2022-01-07 05:26 UTC, Abirpal202049 approved these changes

2022-01-07 06:47 UTC, saikatmu31 approved these changes

2022-01-07 10:49 UTC, thepranaygupta requested changes

2022-01-07 10:49 UTC, thepranaygupta commented on Forms/Contact Us Form_01/README.md
> +![](./assets/preview.gif)
please embed the preview gif directly by drag and drop

2022-01-09 18:49 UTC, nandini7637 commented
@suyogkokaje have you worked on changes?

2022-01-11 09:37 UTC, suyogkokaje commented
@thepranaygupta please have a look.

2022-01-11 15:02 UTC, bhavesh-chaudhari approved these changes

2022-01-12 05:07 UTC, Ovenoboyo approved these changes

2022-01-12 08:00 UTC, merged