Added code for a responsive 0 - 200 range slider.
Dezenix/frontend-html-css-js pull request #79
Opened 2022-01-04 14:13 UTC by kashyap1905

- Related issue : #74 

- Preview : 

![preview](https://user-images.githubusercontent.com/87887741/148071541-132719d4-0d98-4bef-b0f9-348fb26cbb05.gif)

2022-01-04 14:14 UTC, kashyap1905 commented
@thepranaygupta @nandini7637 @Abirpal202049 @saikatmu31 Please review this PR.

2022-01-04 17:39 UTC, thepranaygupta requested changes
remove unnecessary comments and format the code properly

2022-01-04 17:45 UTC, thepranaygupta approved these changes

2022-01-04 17:45 UTC, kashyap1905 commented
@thepranaygupta Made necessary changes as instructed. Please review.

2022-01-05 08:19 UTC, nandini7637 approved these changes

2022-01-07 05:28 UTC, Abirpal202049 approved these changes

2022-01-07 05:28 UTC, merged