Random Quote Generator
Dezenix/frontend-html-css-js pull request #81
Opened 2022-01-05 14:01 UTC by rishitajain01

fixes #30

2022-01-05 17:01 UTC, thepranaygupta requested changes

2022-01-05 17:01 UTC, thepranaygupta commented on randomquotegenerator/style.css
> +}
avoid adding styles directly to HTML tags, use classes instead.

2022-01-06 18:02 UTC, Abirpal202049 approved these changes

2022-01-07 11:10 UTC, thepranaygupta approved these changes

2022-01-07 13:29 UTC, nandini7637 requested changes
Follow the folder structure

2022-01-07 15:14 UTC, Abirpal202049 approved these changes

2022-01-08 14:56 UTC, merged