Fix: Added code for 'Simple Registration Form' (Issue #84)
Dezenix/frontend-html-css-js pull request #85
Opened 2022-01-09 09:08 UTC by kashyap1905

Related Issue: #84 

Previews:

![Image1](https://user-images.githubusercontent.com/87887741/148676132-5656048c-07db-4587-a5a7-63d259c50e95.png)
![Image2](https://user-images.githubusercontent.com/87887741/148676142-150c1318-50dc-4068-a491-7f2d2f655d54.png)
![Image3](https://user-images.githubusercontent.com/87887741/148676148-4dce3498-3cb3-458d-93ed-4dd749199b55.png)
![Image4](https://user-images.githubusercontent.com/87887741/148676150-904025d5-3793-4f37-a01d-e8c048ecd046.png)
![Image5](https://user-images.githubusercontent.com/87887741/148676156-0aa9cfd7-15a3-4cf1-8cc4-780667c3610e.png)

2022-01-09 09:09 UTC, kashyap1905 commented
@thepranaygupta @nandini7637 @Abirpal202049 @saikatmu31 Please review this PR.

2022-01-10 03:28 UTC, Abirpal202049 approved these changes

2022-01-11 05:58 UTC, nandini7637 requested changes
Just put your files in registration form_01
else everything looks good

2022-01-11 07:09 UTC, kashyap1905 commented
@nandini7637 Made changes as directed. Please review the changes.

2022-01-11 15:06 UTC, merged