Added Weather Widget UI Design
Dezenix/frontend-html-css-js pull request #93
Opened 2022-01-15 14:01 UTC by Nidhikumari-4

2022-01-15 14:10 UTC, thepranaygupta requested changes

2022-01-15 14:10 UTC, thepranaygupta commented on Cards/Card_01/code/style.css
> +}
use classes instead of tags to style elements

2022-01-17 05:45 UTC, nandini7637 requested changes
You have added your calendar code, kindly check

2022-01-17 05:53 UTC, Nidhikumari-4 commented
@nandini7637  I had added calendar code by mistake.
I have made the changes kindly check.

2022-01-18 06:23 UTC, Abirpal202049 approved these changes

2022-01-18 17:16 UTC, nandini7637 requested changes
Rename folder as Weather Widget Card, else every thing LGTM

2022-01-18 17:34 UTC, Nidhikumari-4 commented
@nandini7637 I have renamed the folder, kindly check .

2022-01-19 13:20 UTC, nandini7637 approved these changes

2022-01-19 13:21 UTC, merged