Calendar
Dezenix/frontend-html-css-js pull request #97
Opened 2022-01-17 17:57 UTC by Nidhikumari-4

2022-01-17 18:55 UTC, thepranaygupta approved these changes
LGTM

2022-01-18 17:12 UTC, nandini7637 requested changes
1-Add class to body
2- You have added widget card code too kindly check!

2022-01-18 18:06 UTC, Nidhikumari-4 commented
@nandini7637  I have made the required changes, kindly check!

2022-01-19 13:13 UTC, nandini7637 approved these changes

2022-01-25 05:02 UTC, merged